/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Identity */
        get: operations["get_identity_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Provision Tenant */
        post: operations["provision_tenant_api_v1_tenants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Tenant */
        get: operations["get_current_tenant_api_v1_tenants_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Knowledge Bases */
        get: operations["list_knowledge_bases_api_v1_knowledge_bases_get"];
        put?: never;
        /** Create Knowledge Base */
        post: operations["create_knowledge_base_api_v1_knowledge_bases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases/{knowledge_base_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge Base */
        get: operations["get_knowledge_base_api_v1_knowledge_bases__knowledge_base_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases/{knowledge_base_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_api_v1_knowledge_bases__knowledge_base_id__search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases/{knowledge_base_id}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_v1_knowledge_bases__knowledge_base_id__ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases/{knowledge_base_id}/ask/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Stream */
        post: operations["ask_stream_api_v1_knowledge_bases__knowledge_base_id__ask_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/business/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Demo Order */
        get: operations["get_demo_order_api_v1_business_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases/{knowledge_base_id}/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Diagnose */
        post: operations["diagnose_api_v1_knowledge_bases__knowledge_base_id__diagnose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agent Runs */
        get: operations["list_agent_runs_api_v1_agent_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent Run */
        get: operations["get_agent_run_api_v1_agent_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases/{knowledge_base_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Knowledge Base Documents */
        get: operations["list_knowledge_base_documents_api_v1_knowledge_bases__knowledge_base_id__documents_get"];
        put?: never;
        /** Upload Knowledge Base Document */
        post: operations["upload_knowledge_base_document_api_v1_knowledge_bases__knowledge_base_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/index-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Document Index Jobs */
        get: operations["list_document_index_jobs_api_v1_documents__document_id__index_jobs_get"];
        put?: never;
        /** Reindex Document */
        post: operations["reindex_document_api_v1_documents__document_id__index_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Active Document Chunks */
        get: operations["list_active_document_chunks_api_v1_documents__document_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveChunkRead */
        ActiveChunkRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Index Version */
            index_version: number;
            /** Chunk Index */
            chunk_index: number;
            /** Content */
            content: string;
            /** Token Count */
            token_count: number;
            /** Page Number */
            page_number: number | null;
            /** Section Title */
            section_title: string | null;
            /** Section Path */
            section_path: string[];
        };
        /** AgentRunDetail */
        AgentRunDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Knowledge Base Id */
            knowledge_base_id: string | null;
            /** Question */
            question: string;
            /** Model Name */
            model_name: string;
            status: components["schemas"]["AgentRunStatus"];
            /** Outcome */
            outcome: string | null;
            /** Answer */
            answer: string | null;
            /** Error Code */
            error_code: string | null;
            /** Input Tokens */
            input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Total Tokens */
            total_tokens: number | null;
            /** Duration Ms */
            duration_ms: number | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Steps */
            steps: components["schemas"]["AgentRunStepRead"][];
        };
        /**
         * AgentRunStatus
         * @enum {string}
         */
        AgentRunStatus: "RUNNING" | "SUCCEEDED" | "FAILED";
        /** AgentRunStepRead */
        AgentRunStepRead: {
            /** Sequence */
            sequence: number;
            /** Name */
            name: string;
            /** Input Data */
            input_data: {
                [key: string]: unknown;
            };
            /** Output Data */
            output_data: {
                [key: string]: unknown;
            };
            /** Error Code */
            error_code: string | null;
            /** Input Tokens */
            input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Total Tokens */
            total_tokens: number | null;
            /** Duration Ms */
            duration_ms: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AgentRunSummary */
        AgentRunSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Knowledge Base Id */
            knowledge_base_id: string | null;
            /** Question */
            question: string;
            /** Model Name */
            model_name: string;
            status: components["schemas"]["AgentRunStatus"];
            /** Outcome */
            outcome: string | null;
            /** Answer */
            answer: string | null;
            /** Error Code */
            error_code: string | null;
            /** Input Tokens */
            input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Total Tokens */
            total_tokens: number | null;
            /** Duration Ms */
            duration_ms: number | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
        };
        /** AnswerCitation */
        AnswerCitation: {
            /** Number */
            number: number;
            source: components["schemas"]["SearchHit"];
        };
        /** AskRequest */
        AskRequest: {
            /** Query */
            query: string;
            /**
             * Top K
             * @default 10
             */
            top_k: number;
            /**
             * Min Score
             * @default 0.5
             */
            min_score: number;
        };
        /** AskResponse */
        AskResponse: {
            /**
             * Knowledge Base Id
             * Format: uuid
             */
            knowledge_base_id: string;
            /** Answer */
            answer: string;
            /** Grounded */
            grounded: boolean;
            /** Citations */
            citations: components["schemas"]["AnswerCitation"][];
        };
        /** Body_upload_knowledge_base_document_api_v1_knowledge_bases__knowledge_base_id__documents_post */
        Body_upload_knowledge_base_document_api_v1_knowledge_bases__knowledge_base_id__documents_post: {
            /** File */
            file: string;
        };
        /** DiagnoseRequest */
        DiagnoseRequest: {
            /** Question */
            question: string;
            /** Order Id */
            order_id?: string | null;
        };
        /** DiagnoseResponse */
        DiagnoseResponse: {
            /** Run Id */
            run_id?: string | null;
            /**
             * Knowledge Base Id
             * Format: uuid
             */
            knowledge_base_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ANSWERED" | "BUSINESS_FACTS_ONLY" | "NEEDS_ORDER_ID" | "ORDER_NOT_FOUND";
            /** Answer */
            answer: string;
            order: components["schemas"]["OrderSnapshot"] | null;
            /** Citations */
            citations: components["schemas"]["AnswerCitation"][];
        };
        /** DocumentRead */
        DocumentRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Knowledge Base Id
             * Format: uuid
             */
            knowledge_base_id: string;
            /** Filename */
            filename: string;
            /** File Type */
            file_type: string;
            /** Checksum */
            checksum: string;
            status: components["schemas"]["DocumentStatus"];
            /** Active Index Version */
            active_index_version: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DocumentStatus
         * @enum {string}
         */
        DocumentStatus: "UPLOADED" | "PARSING" | "CHUNKING" | "EMBEDDING" | "READY" | "FAILED";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IdentityRead */
        IdentityRead: {
            /** Subject */
            subject: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "viewer";
        };
        /** IndexJobRead */
        IndexJobRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Index Version */
            index_version: number;
            /** Processing Backend */
            processing_backend: string;
            /** Processing Version */
            processing_version: string;
            /** Embedding Model */
            embedding_model: string;
            /** Embedding Space Id */
            embedding_space_id: string | null;
            /** Target Tokens */
            target_tokens: number;
            /** Max Tokens */
            max_tokens: number;
            /** Max Chunks */
            max_chunks: number;
            /** Embed Batch Size */
            embed_batch_size: number;
            /** Tokenizer Name */
            tokenizer_name: string;
            status: components["schemas"]["IndexJobStatus"];
            /** Attempts */
            attempts: number;
            /**
             * Next Attempt At
             * Format: date-time
             */
            next_attempt_at: string;
            /** Lease Expires At */
            lease_expires_at: string | null;
            /** Last Error */
            last_error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * IndexJobStatus
         * @enum {string}
         */
        IndexJobStatus: "PENDING" | "RUNNING" | "SUCCEEDED" | "FAILED";
        /** KnowledgeBaseCreate */
        KnowledgeBaseCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** KnowledgeBaseRead */
        KnowledgeBaseRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            status: components["schemas"]["KnowledgeBaseStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * KnowledgeBaseStatus
         * @enum {string}
         */
        KnowledgeBaseStatus: "ACTIVE" | "ARCHIVED";
        /** OrderSnapshot */
        OrderSnapshot: {
            /** Order Id */
            order_id: string;
            payment_status: components["schemas"]["PaymentStatus"];
            /** Total Amount Cents */
            total_amount_cents: number;
            /** Refundable Amount Cents */
            refundable_amount_cents: number;
            /** Currency */
            currency: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Refund Attempts */
            refund_attempts: components["schemas"]["RefundAttemptSnapshot"][];
        };
        /**
         * PaymentStatus
         * @enum {string}
         */
        PaymentStatus: "PAID" | "UNPAID" | "REFUNDED";
        /** RefundAttemptSnapshot */
        RefundAttemptSnapshot: {
            /** Attempt Number */
            attempt_number: number;
            status: components["schemas"]["RefundStatus"];
            /** Reason Code */
            reason_code: string | null;
            /** Amount Cents */
            amount_cents: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * RefundStatus
         * @enum {string}
         */
        RefundStatus: "PENDING" | "FAILED" | "SUCCEEDED";
        /** SearchHit */
        SearchHit: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Document Name */
            document_name: string;
            /** Index Version */
            index_version: number;
            /** Chunk Index */
            chunk_index: number;
            /** Content */
            content: string;
            /** Score */
            score: number;
            /** Page Number */
            page_number: number | null;
            /** Section Title */
            section_title: string | null;
            /** Section Path */
            section_path: string[];
        };
        /** SearchRequest */
        SearchRequest: {
            /** Query */
            query: string;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
            /**
             * Min Score
             * @default 0
             */
            min_score: number;
        };
        /** SearchResponse */
        SearchResponse: {
            /**
             * Knowledge Base Id
             * Format: uuid
             */
            knowledge_base_id: string;
            /** Hits */
            hits: components["schemas"]["SearchHit"][];
        };
        /** TenantCreate */
        TenantCreate: {
            /** Name */
            name: string;
        };
        /** TenantRead */
        TenantRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_identity_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityRead"];
                };
            };
        };
    };
    provision_tenant_api_v1_tenants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_tenant_api_v1_tenants_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantRead"];
                };
            };
        };
    };
    list_knowledge_bases_api_v1_knowledge_bases_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_knowledge_base_api_v1_knowledge_bases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeBaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_base_api_v1_knowledge_bases__knowledge_base_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_knowledge_bases__knowledge_base_id__search_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_api_v1_knowledge_bases__knowledge_base_id__ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_stream_api_v1_knowledge_bases__knowledge_base_id__ask_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_demo_order_api_v1_business_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diagnose_api_v1_knowledge_bases__knowledge_base_id__diagnose_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiagnoseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnoseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agent_runs_api_v1_agent_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_run_api_v1_agent_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_base_documents_api_v1_knowledge_bases__knowledge_base_id__documents_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                knowledge_base_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_knowledge_base_document_api_v1_knowledge_bases__knowledge_base_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_knowledge_base_document_api_v1_knowledge_bases__knowledge_base_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_document_index_jobs_api_v1_documents__document_id__index_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexJobRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reindex_document_api_v1_documents__document_id__index_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_active_document_chunks_api_v1_documents__document_id__chunks_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveChunkRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
